### ISSUE TITLE
配置了log_dir 但是控制台页面显示的地址还是默认的

### ISSUE THREAD

**Issue by KingDracula** [X-Profiler/xprofiler#109]
![image](https://user-images.githubusercontent.com/13584613/144554950-18a088f7-0af0-4dc7-9690-e54dd6c3668a.png)
![image](https://user-images.githubusercontent.com/13584613/144555149-c8ed177f-b281-46ff-8c59-277595a59cba.png)

**Comment by hyj1991** [comment]
xprofiler 插件的 logdir 和 xtransit 的是两个配置，你修改了 xtransit 的 logdir，那么 xprofiler 启动的时候也要指定 logdir

建议你看下架构图来理解下这两者的作用。

**Comment by KingDracula** [comment]
![image](https://user-images.githubusercontent.com/13584613/144556939-3f011d80-ad0d-474d-b755-08809cf8518f.png)
按照文档配置了xprofiler的log_dir

**Comment by hyj1991** [comment]
xprofiler 只能写全路径
