### ISSUE TITLE
关于windows环境下日志收集的问题

### ISSUE THREAD

**Issue by hcfw007** [X-Profiler/xprofiler#119]
据我所知现在在windows环境下日志收集的功能是有限的，请问一下具体是哪一部分尚不可用？
我在windows环境部署的目前只能收集到cpu、内存等基础信息，这是正常现象吗？火焰图、进程信息现在可用吗？

**Comment by hyj1991** [comment]
你是在哪里看到 windows 环境下日志收集功能是有限的？

**Comment by hcfw007** [comment]
哦，在xtransit那边你回复说```report core```这个能力 windows 的其实还在开发中，源码中也有一些地方标了windows not supported。也可能是我没理解对。

**Comment by hyj1991** [comment]
> 哦，在xtransit那边你回复说`report core`这个能力 windows 的其实还在开发中，源码中也有一些地方标了windows not supported。也可能是我没理解对。

极少一部分 windows 不支持，目前一个是 core 文件上报，另一个是磁盘信息

**Comment by hyj1991** [comment]
进程相关的全部都是支持的

**Comment by hyj1991** [comment]
core 文件是因为 windows 下的 corefile 格式和 unix 区别比较大，需要先看下能不能配置 core pattern 或者生成位置有什么约定才能做，磁盘信息是我没找到 windows 下 cmd 获取可读性比较好的磁盘信息列表的指令

你要是有兴趣完善下 windows 这两块的数据可以来个 pr

**Comment by hcfw007** [comment]
好的，感谢回答。所以如果配置正确，进程信息和火焰兔都是可用的吗？

**Comment by hyj1991** [comment]
> 好的。所以如果配置正确，火焰兔也是可用的咯。懂了，我会研究一下这两款的，感谢回答。

对，进程相关的全部都是可用的，如果 windows 下有问题你可以提 issue，我来修下
