### ISSUE TITLE
[WIP]  支持 worker threads

### ISSUE THREAD

**Issue by hyj1991** [X-Profiler/xprofiler#120]
## 背景

worker threads 已经基本成熟，目前的 xprofiler 专注于 nodejs 进程级别监控，缺少对 worker thread 的数据监控与对应的 profiling 能力。

## 方案

目前看需要可能进行两部分的改造：
* 支持在 main thread 和 worker thread 中多次重复引入 `xprofiler` 插件
* 由于 worker thread 处于单独的 v8::Isolate 中，需要抽象使用到的 v8 value 静态结构

另外需要对控制台前端进行交互模型优化，将开启了 worker threads 的 nodejs 进程进行对应的 thread 交互展示。

## PR 列表
* [x] https://github.com/X-Profiler/xprofiler/pull/122
* [x] https://github.com/X-Profiler/xprofiler/pull/124
* [x] https://github.com/X-Profiler/xprofiler/pull/129
* [x] https://github.com/X-Profiler/xprofiler/pull/130
* [x] https://github.com/X-Profiler/xprofiler/pull/131
* [x] https://github.com/X-Profiler/xprofiler/pull/132
* [x] https://github.com/X-Profiler/xprofiler/pull/133
* [x] https://github.com/X-Profiler/xprofiler/pull/140
* [x] https://github.com/X-Profiler/xprofiler/pull/147
* [x] https://github.com/X-Profiler/xprofiler/pull/148
* [x] 日志针对 thread 输出
* [x] Dump actions 支持 thread

**Comment by legendecas** [comment]
# Objectives
- 支持对于 worker_threads 的 Worker 进行诊断操作；
- 支持输出 worker_threads 的 Worker 的 JavaScript 线程信息；

# Status Quo

## 工作线程

目前 xprofiler 在静默状态下，共有 2 个额外线程：
1. Log 线程：定时输出 xprofiler 日志，包含：
	1. 进程 CPU 用量信息，
	2. 进程内存用量信息，
	3. JavaScript Heap 用量信息，
	4. JavaScript Heap GC 统计，
	5. uv loop 中的 handle 信息，
	6. Node.js HTTP 统计；
2. 诊断指令监听线程：
	1. 在执行部分指令时，会临时创建一个 watchdog 线程用于计时、停止长时间执行的操作，
	2. 在指令分发完完成之后，会临时创建一个回调线程用于将指令分发结果返回给指令发起进程；

## 配置/启动

目前，xprofiler 的配置可以在 Node.js 主线程通过 JavaScript API 写入 C++ Native Static 存储。

Log 线程与诊断指令监听服务通过 JavaScript API 启动。启动后这些工作线程都将占用 C++ Native Static 存储位，无法重复启动、兼容多个 JavaScript 线程。

## 诊断操作支持

在通过 JavaScript API 启动时，xprofiler addon 启动一个新工作线程用于诊断指令监听服务。在监听服务接收到诊断指令后，会通过 async 与 interrupt 请求 JavaScript 主线程中断、并将指令转移给 JavaScript 线程，并在中断中执行诊断指令。

在将指令转移给 JavaScript 线程执行后，将指令分发结果（如诊断文件路径、指令id、版本号信息等等）通过一个临时 IPC 线程返回给指令发起进程。

## 指标采集/日志输出

在启动时，启动一个日志线程用于专用的工作线程。这个工作线程每隔 1s 采集一次 CPU 信息，每隔 1 分钟发起一次 JavaScript 线程指标采集与（1s后）输出日志。目前，向 JavaScript 线程发起指标采集的指令时并没有使用 Isolate::RequestInterrupt，也就是说如果在 JavaScript 线程阻塞的情况下则 JavaScript 线程指标不会更新。

其中，像进程 CPU 用量、进程内存用量等等都是进程级别指标，JavaScript Heap、GC、uv handle、http 等统计都是 Node.js Environment 级别的指标。

# Design


## 配置
目前 xprofiler native 配置包含以下几项：

1. `log_dir`: 日志目录；
1. `log_interval`: 日志周期；
1. `log_level`: 日志登记；
1. `log_type`: 日志类型，如文件输出、标准输出等；
1. `enable_log_uv_handles`: 日志输出 uv handle 信息；
1. `log_format_alinode`: 日志输出为 alinode 格式；
1. `enable_fatal_error_hook`: 替换 Node.js 自身的 Isolate Fatal Error Handler 为 xprofiler 提供的 handler，用于在 Isolate fatal error 时生成诊断报告；
1. `patch_http`: 向 Node.js builtin http 模块注入指标采集，在 Native 侧没有使用，主要用于 xprofctl 通过 IPC 获取当前进程配置；
1. `patch_http_timeout`: Ditto；
1. `check_throw`: 如果 xprofiler socket path 过长则抛出异常，在 Native 侧没有使用，主要用于 xprofctl 通过 IPC 获取当前进程配置；

可以看出这些配置通常都是进程级别的配置，为了简化配置模型，可以增加如下限制：
1. 只能在 JavaScript 主线程写入配置，并且无法在启动后修改；
2. JavaScript Worker 线程只能读取配置；

## 启动
xprofiler 需要在每一个 JavaScript Environment 中都通过 JavaScript API 初始化一次（可以通过 Worker instruments 不需要用户来调用）。

只有在 JavaScript 主线程中初始化时，会启动 Log 线程与指令监听线程，并创建全局 xprofiler 环境。

在非 JavaScript 主线程初始化时，只会向全局 xprofiler 环境中以 Node.js Worker Thread Id 注册当前 JavaScript 线程。同时，需要通过 `node::AtExit(Environment*, cb, arg)` 注册退出回调用于销毁 xprofiler 中的注册。

## Per Environment Data

目前，xprofiler 中对于 JavaScript 主线程特有的数据如指标暂存、指令暂存等等都是直接通过 static 变量存储。在增加了多 worker threads 支持后，这些 static 存储将不再能准确地描述多线程模型。

因此我们需要增加一个 xprofiler 全局的注册表：

```c++
namespace xprofiler {

class EnvironmentRegistry;

namespace per_process {
extern EnvironmentRegistry registry;
}
}
```

对于每一个启用 xprofiler 的 JavaScript 线程，都需要创建一个对应的 `EnvironmentData` 并向 `EnvironmentRegistry` 上注册：

```c++
namespace xprofiler {
class EnvironmentData;
}
```

`EnvironmentData` 的生命周期需要通过 `node::AtExit` 绑定到 Environment 上。

## 诊断操作
所有的诊断操作都应该指定 Node.js Worker Thread Id 以区分诊断目标。

为了兼容目前的 xprofctl 指令，没有指定 thread id 的情况下则以 JavaScript 主线程（threadId=0）为诊断目标。

在分发诊断操作时，需要通过查找 xprofiler 全局的环境注册来确定目标 thread 是否存在、能否执行。

在引入 worker threads 后，在执行诊断操作的过程中目标 threads 都有可能因为各种原因退出。通常情况下，如果是 recoverable 异常（如 JavaScript 异常等）则可以通过 `node::AtExit` 获取回调并终结诊断资源（如 watchdog 等）。如果是非 recoverable 异常则应该需要触发 fatal error 来 abort 整个进程。

## 指标采集

在 Log 线程，需求严格区分进程指标与 JavaScript 线程指标：

进程指标：
1. 进程 CPU 用量信息；
2. 进程内存用量信息；

JavaScript 线程指标：
1. JavaScript Heap 用量信息，
2. JavaScript Heap GC 统计，
3. uv loop 中的 handle 信息，
4. Node.js HTTP 统计；

对于进程指标，可以直接在 Log 线程采集（目前也是在 Log 线程采集 CPU 信息）。

对于 JavaScript 线程指标，需要遍历 xprofiler 的全局环境，向每一个线程都触发指标采集。

## 日志输出
日志输出时，需要增加一个 tid 标签：

```
[YYYY-MM-DD HH:mm:ss] [日志级别] [日志类型] [pid] [tid] [xprofiler 版本] 日志详情
```

格式变化需要 xtransit 及后序处理同时改动。

**Comment by hyj1991** [comment]
这个方案整体看起来没有什么问题，对于日志的更改：

```bash
[YYYY-MM-DD HH:mm:ss] [日志级别] [日志类型] [pid] [tid] [xprofiler 版本] 日志详情
```

这里可能会造成 xtransit 解析的不兼容，因为可能会出现新的 xprofiler 插件搭配旧的 xtransit 的场景，我想想看怎么升级，或者直接发个 xprofiler@2.0 的大版本，注明是 break change

Reference：https://github.com/X-Profiler/xtransit/blob/master/orders/xprofiler_log.js

**Comment by hyj1991** [comment]
cc @atian25 @fengmk2 ，支持 worker threads 后，Egg 3 的 agent 模型可以考虑使用 worker 来实现了

**Comment by fengmk2** [comment]
> cc @atian25 @fengmk2 ，支持 worker threads 后，Egg 3 的 agent 模型可以考虑使用 worker 来实现了

那就太棒了，说不定内存变量共享也变得可能。

**Comment by hyj1991** [comment]
在 `xprofiler@2.x` 已经落地，且 2.x 已经推送至 latest tag
