### ISSUE TITLE
[WIP] 提供 linux-arm64 预编译包

### ISSUE THREAD

**Issue by hyj1991** [X-Profiler/xprofiler#126]
为服务器国产化浪潮做准备，以及目前的 Apple Arm 芯片下安装 linux 提升前端编译性能等场景，计划提供 `linux-arm64` 的预编译包，使得 `xprofiler` 插件可以方便应用到更多场景下。

**Comment by fengmk2** [comment]
GitHub 好像支持 linux arm64

**Comment by hyj1991** [comment]
> GitHub 好像支持 linux arm64

github actions 运行时库好像和正常的不太一样，上次我试了下走 action auto release，编译出来的 binary 在普通的 linux 机器上没办法使用

**Comment by hyj1991** [comment]
`xprofiler@v1.4.0` 开始已经支持 linux-arm64 预编译包: https://github.com/X-Profiler/xprofiler/releases/tag/v1.4.0
