### ISSUE TITLE
xprofiler_binary_host_mirror 

### ISSUE THREAD

**Issue by stardustman** [X-Profiler/xprofiler#144]
npm i xprofiler --save --xprofiler_binary_host_mirror=https://npm.taobao.org/mirrors/xprofiler
`https://npm.taobao.org`  这个域名快失效了吧

**Comment by hyj1991** [comment]
> https://www.yuque.com/hyj1991/easy-monitor/application

最新的以官方文档为准，文档里之前就更新了
