### ISSUE TITLE
作者为什么不考虑使用n-api 开发binding层呢？

### ISSUE THREAD

**Issue by liSong5713** [X-Profiler/xprofiler#150]
如题：[n-api](http://nodejs.cn/api/n-api.html)

**Comment by hyj1991** [comment]
你对 N-API 真正的作用了解吗？

**Comment by liSong5713** [comment]
最近在学习通过c++ 开发bingding层，有很多不了解的。 比如NAN 到N-API ,node-gyp=>CMake.js，所以想请教下作者大大为什么没有使用官方最新的技术栈

**Comment by hyj1991** [comment]
理解下 ABI 兼容性就不会有这个问题了，N-API 并不是 Nan 的替代哦

**Comment by liSong5713** [comment]
感谢大佬解答，麻烦再请教下通过什么途径编译多个不同系统的编译包呢？
<img width="889" alt="截屏2022-03-15 下午8 22 45" src="https://user-images.githubusercontent.com/19524010/158376928-5205fc66-b97a-4038-b021-0d73cbecab77.png">
