### ISSUE TITLE
和prom-client的比较以及一些疑惑

### ISSUE THREAD

**Issue by XiaocongDong** [X-Profiler/xprofiler#165]
很棒的监控平台!

看了文档和教程这里想问作者一些问题

## 和prom-client的区别？
这里作者用了C++ Addon的方式去采集CPU用量和内存用量等指标，我们团队现在用的是[prom-client](https://github.com/siimon/prom-client/tree/master/lib/metrics)的默认指标，我大概看了一些prom-client的源码，好像是基于Node perf-hooks或者诸如process.cpuUsage的原生API来完成这类信息的采集的，所以这里想请教一下C++ Addon的方式和prom-client的方式比起来的优点是什么？

## C++ Addon 采集CPU的profile和NodeJS的inspector比起来有什么优点？
我们之前一直用NodeJS原生的[inspector](https://nodejs.org/api/inspector.html#cpu-profiler)来采集Node的CPU信息，发现有一个问题就是：当应用的CPU被某些东西阻塞住时，采集会很慢，甚至采不了，不知道C++ Addon的方式来采集是不是可以解决这个问题？

## C++ Addon 采集heap的方式和heapdump比较？
[heapdump](https://www.npmjs.com/package/heapdump)也可以采集应用的heap信息，这种方式和你的方式又有什么不一样呢？

**Comment by hyj1991** [comment]
采集放到 uv thread 中，对 js 工作线程性能影响可以忽略不急，另外解决了你提到的 js 工作线程阻塞时无法工作的问题（`RequestInterrupt`），另外将 gc profiling / cpu profiling / heap profiling / heapdump / diag report 等诊断能力全部集成，无需安装多个模块，并且可以通过 cmd 指令在外部通知进程进行各种状态导出（不管 js 是否阻塞）

**Comment by hyj1991** [comment]
更多的，我们已经支持了对 `worker thread` 的支持

**Comment by XiaocongDong** [comment]
> 更多的，我们已经支持了对 `worker thread` 监控的支持

想问一下怎么体现出对`worker thread`监控的支持的呢？

**Comment by hyj1991** [comment]
> 想问一下怎么体现出对worker thread监控的支持的呢？

性能日志里会有 worker thread id 对应的线程数据信息
