### ISSUE TITLE
[WIP] 集成 google coredumper

### ISSUE THREAD

**Issue by hyj1991** [X-Profiler/xprofiler#169]
解决以下问题：

* 手动执行时 `gcore` 需要 root 用户
* 部分容器需要在特权模式下运行才可以生成

Reference：https://github.com/x-profiler/coredumper

**Comment by hyj1991** [comment]
测试生成的 core lldb 可读

**Comment by fengmk2** [comment]
有点厉害，每个细分领域都做到这么专业了。

**Comment by hyj1991** [comment]
> 有点厉害，每个细分领域都做到这么专业了。

现在这个库只能支持到 linux，不过也足够使用了，这样可以无需再使用需要 root 权限的 `gcore` 对线上进程动态生成 core file
