### ISSUE TITLE
feature request: 自定义.profiler文件的位置

### ISSUE THREAD

**Issue by TooBug** [X-Profiler/xprofiler#185]
查看了代码，目前运行时会在home目录下生成一个`.profiler`文件，保存的是进程的一些信息，看起来是不同组件之间通信的一个渠道。目前无选项可定义这个文件的位置，即便`XPROFILER_UNIT_TEST_TMP_HOMEDIR`环境变量也只在单元测试时生效。

我们碰到的问题：容器中运行时无权限写home目录，导致应用启动失败。所以希望这里有能自定义这个数据文件的选项。

另外也建议对该文件机制进行一些说明，比如是全局的而不是应用级别的，如果自定义的话应该放到与项目代码不关联的位置等等。

**Comment by hyj1991** [comment]
这个目录跟改的话，xtransit 执行指令的时候的也得改，理解起来会有成本，我想想怎么处理更好一些

另外，`os.tmodir()` 的权限应该有吧

**Comment by TooBug** [comment]
更新一下：home目录没有写权限本身是不太正常的，于是我去问了一下我们运维同事，确实是机制有问题导致找错home目录。目前我这边的问题是解决了。

不过issue本身，是否要做成可自定义的，建议可以纳入考虑。

**Comment by hyj1991** [comment]
是否做成自定义，其实和运行进程的用户是否有权限读写自己的 home 目录有关系，理论上启动的 web 用户是应该有权限去读写自己用户所处的 home 目录的

**Comment by hyj1991** [comment]
这个我暂时关闭，后面看情况是否有必要支持这种自定义的能力
