### ISSUE TITLE
xprofiler_binary_host_mirror 使用yarn安装，是否可以加速

### ISSUE THREAD

**Issue by cnmission** [X-Profiler/xprofiler#187]
使用`yarn add xprofiler`，设置`xprofiler_binary_host_mirror=https://npmmirror.com/mirrors/xprofiler`可以生效吗？观察设置前后安装速度没有变化
另外，如果yarn无法使用该参数加速，那么访问地址是github.com吗？

**Comment by hyj1991** [comment]
不使用 `yarn` 所以无法回答此问题，不过如果 mirror 不生效，访问的原始地址确实是 github release page 里对应的预编译好的 binary :)
