### ISSUE TITLE
[BUG] 演示链接已经无法打开

### ISSUE THREAD

**Issue by atom-7** [X-Profiler/xprofiler#236]
语雀文档的大部分图也已经烂了,不维护了吗

**Comment by hyj1991** [comment]
你如果真的想使用，跑下 all-in-one 就能看到效果了

**Comment by hyj1991** [comment]
3 年服务器到期了，需要有空才能重新部署下。

**Comment by hyj1991** [comment]
另外看了下，语雀的文档上图片并没有挂，可以确认下是不是你的网络有问题。

**Comment by atom-7** [comment]
> 另外看了下，语雀的文档上图片并没有挂，可以确认下是不是你的网络有问题。

感谢,确实没问题(手机5g访问),  应该是我这边宽带dns解析有问题
