### ISSUE TITLE
[WIP] linux 下增加 ptmalloc 的配置缓解 rss 无法回收的情况

### ISSUE THREAD

**Issue by hyj1991** [X-Profiler/xprofiler#237]
原因参见：https://zhuanlan.zhihu.com/p/675317993

参考资料
* https://zhuanlan.zhihu.com/p/560341532
* https://zhuanlan.zhihu.com/p/399210650

MR
* https://github.com/X-Profiler/xprofiler/issues/237

**Comment by fengmk2** [comment]
用上 ezm 就能默认解决！

**Comment by hyj1991** [comment]
> 用上 ezm 就能默认解决！

默认还是打算 `false`，有需要的再打开
