### ISSUE TITLE
插件架构和实现原理是否有计划对外分享呢？

### ISSUE THREAD

**Issue by kekobin** [X-Profiler/xprofiler#70]
大佬，插件架构和实现原理是否有计划对外分享呢？挺想知道xprofiler对宿主进程日志收集时是否会影响到宿主进程的性能等

**Comment by hyj1991** [comment]
采集内核数据包括日志写入都在 uv thread 里进行，旁路操作对主进程的影响微乎其微，具体设计架构后面会分享的

**Comment by kekobin** [comment]
> 采集内核数据包括日志写入都在 uv thread 里进行，旁路操作对主进程的影响微乎其微，具体设计架构后面会分享的

好的，期待！
