### ISSUE TITLE
error: Cannot find module 'xx/node_modules/xprofiler/build/binding/Release/node-v64-linux-x64/xprofiler.node'

### ISSUE THREAD

**Issue by kekobin** [X-Profiler/xprofiler#72]
```
npm install egg-xtransit --save --xprofiler_binary_host_mirror=https://npm.taobao.org/mirrors/xprofiler
```
大佬，我用上面的命令windows上安装得到的是 node-v64-win32-x64 版的xprofiler.node，但是在ubuntu上安装时得到的是 node-v57-linux-x64  版的xprofiler.node，然后在业务代码中报如下错误：    
```
/xx/node_modules/egg-xtransit/agent.js, error: Cannot find module 'xx/node_modules/xprofiler/build/binding/Release/node-v64-linux-x64/xprofiler.node'
```

不知道这个版本是根据什么生成的呢，导致了这些差异？

**Comment by hyj1991** [comment]
你执行 npm install 的 node 版本和运行 xtransit 的 node 版本不一致。

**Comment by kekobin** [comment]
> 你执行 npm install 的 node 版本和运行 xtransit 的 node 版本不一致。

这个版本差异这么大的么？例如我的业务是通过一台构建机构建出node_modules，然后各个环境同步这份node_modules，这种情况确实是业务机跟构建机node版本有所不同。也就是说运行和安装必须的保持同版本才行么？

**Comment by hyj1991** [comment]
> > 你执行 npm install 的 node 版本和运行 xtransit 的 node 版本不一致。
> 
> 这个版本差异这么大的么？例如我的业务是通过一台构建机构建出node_modules，然后各个环境同步这份node_modules，这种情况确实是业务机跟构建机node版本有所不同。也就是说运行和安装必须的保持同版本才行么？

当然，addon 都有这个问题，因为 v8 和 libuv 自身就不保证 abi 兼容

**Comment by kekobin** [comment]
> > > 你执行 npm install 的 node 版本和运行 xtransit 的 node 版本不一致。
> > 
> > 
> > 这个版本差异这么大的么？例如我的业务是通过一台构建机构建出node_modules，然后各个环境同步这份node_modules，这种情况确实是业务机跟构建机node版本有所不同。也就是说运行和安装必须的保持同版本才行么？
> 
> 当然，addon 都有这个问题，因为 v8 和 libuv 自身就不保证 abi 兼容

好的，thx！

**Comment by hyj1991** [comment]
Node.js 内部有一个 module version 字段来标识 abi 兼容的部分，你可以访问 `process.versions.modules` 看到，这个字段一致的 addon 可以通用无需重新编译。

这也就是你看到的 `node-v64-linux-x64/xprofiler.node` 里面的 `v64`，`v57` 的含义

**Comment by kekobin** [comment]
> Node.js 内部有一个 `NODE_MODULE_VERSION` 宏（定义在 `node_version.h` 中）来标识 abi 兼容的版本区间，你也可以用 node 执行 `process.versions.modules` 看到，这个字段一致的 addon 因为内核确认了 abi 兼容所以可以通用无需重新编译。
> 
> 这也就是你看到的 `node-v64-linux-x64/xprofiler.node` 里面的 `v64`，`v57` 的含义

好的~
