### ISSUE TITLE
如果待采集经常一直处于繁忙状态，是否影响采集精准度

### ISSUE THREAD

**Issue by miser** [X-Profiler/xprofiler#75]
比如某个服务器一直无法响应新的请求，可能某个方法持续占用CPU造成了卡顿现象。
那么管理平台再命令该服务器生成CPU火焰图，此刻还能精准获取该阶段的CPU使用情况吗？
我的理解是服务器（该进程）在此过程中无法立即响应管理平台的命令导致错过捕获CPU使用情况的时间点，
不知道我说的问题存在吗？

**Comment by hyj1991** [comment]
不会，不管是内核性能日志采集还是接受控制信令，都在 uv thread 里执行，你的主线程该干啥干啥

**Comment by hyj1991** [comment]
你可以尝试下写个 `while` 死循环（没有比这更让你的主进程无法响应的情况了），然后观察几分钟看看控制台的数据，以及做个 `Node.js 实时诊断报告` 分析就理解我说的了

**Comment by miser** [comment]
刚刚本地部署试了下确实可以正常捕获。

之前自己在做类似alinode的监控时候，生成CPU火焰图存在我自己说的问题，所以用另一个node进程去做的，现在看来不合理

晚点扒一扒这里的源码 学习下
