### ISSUE TITLE
有没有办法不走node-pre-gyp去加速

### ISSUE THREAD

**Issue by uknowzheng** [X-Profiler/xprofiler#80]
由于公司内网不能访问 https://npm.taobao.org/mirrors/ 这个xprofiler镜像源，npm包是可以正常拉取的。能否直接走编译处理。。。。确实没办法了。。。。。。o(╥﹏╥)o

**Comment by hyj1991** [comment]
镜像访问失败会走 local compile 啊

**Comment by hyj1991** [comment]
而且你也可以把  binary 拉下载在公司自己搞个镜像服务器，`--xprofiler_binary_host_mirror` 指向你自己的镜像服务器就行了

**Comment by uknowzheng** [comment]
> 而且你也可以把 binary 拉下载在公司自己搞个镜像服务器，`--xprofiler_binary_host_mirror` 指向你自己的镜像服务器就行了
> 
> 镜像是为了 windows 和线上 linux 服务器考虑，绝大部分线上 linux 服务器没有安装编译环境。

明白了。我看了下源码应该没啥问题，另外再请教个问题，就是如果我直接用编译好的二进制，这块还会依赖操作系统本身的那些gcc的动态链接库吗？

**Comment by hyj1991** [comment]
会，但是 Glibc 版本兼容就行，所以在 7u 上编译出来的 binary 不能给 6u 用，反过来是可以的。

**Comment by hyj1991** [comment]
另外，如果你的安装机器有编译环境，也可以直接带一个 `--build-from-source` 的 flag 就可以强制使用本地编译了。
