### ISSUE TITLE
是否考虑监控事件循环的延迟

### ISSUE THREAD

**Issue by zhangwinning** [X-Profiler/xprofiler#82]
在 node.js 中最好是避免写阻塞当前线程的同步代码，因为 node 是单线程，如果长时间阻塞当前线程就不能处理其他事情，比如某些 CPU 密集型函数(一些 hash 函数，bcrypt.hash等等)，这些往往是无法避免的，因此我认为 xprofiler 中应该添加一些处理信息。

这里有两个例子，说明我上面提出问题
例子 1
```
const interval = 1000
function measureLag(iteration) {
  const start = new Date()
  setTimeout(() => {
    const lag = new Date() - start - interval
    console.log(`Loop ${iteration} took\t${lag} ms`)
    measureLag(iteration + 1) // Recurse
  }, interval)

  // 如果这里有复杂计算且计算时间超过 1000 ms，就会阻塞当前线程，setTimeout 就会延迟 。
  let i = 0
  while (i++ < 10000){}
}
measureLag(1)
```
例子2
https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/#timers

另外，如果您觉的这个 pr 合理的话，有空时间我会加上它。

**Comment by hyj1991** [comment]
正如你所说的，event loop 反映在单个 tick 同步计算耗时比较长，但是如果引发了吞吐量问题此时一定 CPU 会相应飙高触发告警，而假如是偶尔的 tick 耗时长并不影响

**Comment by hyj1991** [comment]
我在一开始考虑过这个 metric，不过实际运行状况中 loop 延时和进程 cpu 指标其实是重复的，所以没做。

**Comment by hyj1991** [comment]
不过这里的例子中定时器延时耗费比较多没有准确执行倒是可以看看有么有办法做一些提示，单纯的 loop 耗费也可以做，这块具体你打算使用什么方式来采集呢？

**Comment by zhangwinning** [comment]
1. 引起事件循环延迟，我现在能想到的也就是计算延迟。。。CPU 的监控确实也可以做到。
2. 定时器的事件循环采集我也没想到好的方法，应该像是例子二这样的情况是可以采集到的。

**Comment by hyj1991** [comment]
> 1. 引起事件循环延迟，我现在能想到的也就是计算延迟。。。CPU 的监控确实也可以做到。
> 2. 定时器的事件循环采集我也没想到好的方法，应该像是例子二这样的情况是可以采集到的。

用 JS Timer 计算 delay 这个数据应该不准确吧，UV_RUN_DEFAULT 下还要减掉 epoll / kequeue 的 sleep time

**Comment by hyj1991** [comment]
得去看看 libuv 有没有提供钩子可以采集的

**Comment by zhangwinning** [comment]
> > 1. 引起事件循环延迟，我现在能想到的也就是计算延迟。。。CPU 的监控确实也可以做到。
> > 2. 定时器的事件循环采集我也没想到好的方法，应该像是例子二这样的情况是可以采集到的。
> 
> 用 JS Timer 计算 delay 这个数据应该不准确吧，UV_RUN_DEFAULT 下还要减掉 epoll / kequeue 的 sleep time

不太清楚 UV_RUN_DEFAULT下还要减掉 epoll / kequeue 的 sleep time？ 这个 sleep 是干啥的？

**Comment by hyj1991** [comment]
epoll_wait / kevent 的耗时，这部分不属于 event loop 的开销

**Comment by hyj1991** [comment]
这里最精确的计算方式应该是，uv_run 整个函数的耗时剪掉 io_poll 阶段的 epoll_wait / kevent 时间，就是每个 tick 的耗时

**Comment by zhangwinning** [comment]
想起个问题，阻塞当前线程的同步代码应该有两种情况
1. 上面提到的 cpu 密集型计算
2. 一些阻塞 I/O 的同步函数，例如fs.readFileSync

**Comment by hyj1991** [comment]
> 想起个问题，阻塞当前线程的同步代码应该有两种情况
> 
> 1. 上面提到的 cpu 密集型计算
> 2. 一些阻塞 I/O 的同步函数，例如fs.readFileSync

下面这个不是阻塞，readFile 是线程池模拟的，阻塞的含义是，JS 主线程一直等待当前任务结束才能进行下一个，readFile 可不会阻塞 JS 主线程

**Comment by zhangwinning** [comment]
谢谢告知，查了一下，确实是这样

**Comment by JunweiSUN** [comment]
> 

请问readFile的sync版本也不会阻塞主线程吗？

**Comment by hyj1991** [comment]
> > 
> 
> 请问readFile的sync版本也不会阻塞主线程吗？

这个会阻塞

**Comment by JunweiSUN** [comment]
> > > 
> > 
> > 
> > 请问readFile的sync版本也不会阻塞主线程吗？
> 
> 这个会阻塞

多谢，刚才看了上面的讨论有点疑惑。
