### ISSUE TITLE
线上环境报错：  Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by SKHon** [X-Profiler/xprofiler#94]
问题描述：
1. 环境：我自己电脑。  
   我本地开发，用的xprofiler的源码，然后npm publish发到我们公司自己的registry上。

2. 环境：构建机器A。
   引入xprofiler包的项目构建，会进行npm i --registry=我们公司的registry。 这个时候，会进行在打包机上进行c++二进制编译。

3. 环境：线上机器B
   在线上跑项目的时候，就会报  Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found。看了一下线上机器确实没有3.4.20版本的GLIBCXX

我的问题：我理解二进制编译的时候是在构建机器A上进行构建的，其glibc版本应该是3.4.20. 而线上机器B的GLIBC版本最高为3.4.19，所以会报这个错。   我想在我本地进行二进制编译，然后传到我们公司registry上，不在构建机器A上进行编译，这样只要我本地的glibc和线上的glibc保持一致，就应该没问题了，那我该怎么配置一下呢？

**Comment by hyj1991** [comment]
公共 Registry 里面已经编译好了各个版本的 binary，直接用

**Comment by SKHon** [comment]
有链接吗，给我发一下

**Comment by Claude-Ray** [comment]
https://npm.taobao.org/mirrors/xprofiler

可以直接设镜像
npm config set xprofiler_binary_host_mirror https://npm.taobao.org/mirrors/xprofiler

**Comment by SKHon** [comment]
GLIBCXX_3.4.20  这个我是需要安装xprofiler的哪个二进制版本呢

**Comment by Claude-Ray** [comment]
根据 Node.js 版本对应的 ABI 版本来选，与编译环境无关，例如 12.x.x 选 v72

但更建议你把所有二进制文件下载到自己的镜像服务器，通过 xprofiler_binary_host_mirror 指定地址，这样 node-pre-gyp 会自动选择需要的版本
